language: python
python:
- '3.5'
install:
- pip install slackclient
- pip install urllib3
script: "./unittests"
notifications:
  slack:
    secure: jMJ5MLZsVBf9265pj5pnKevZIzcwDwytVbJC9w07i1gNDx1omOE1x+e109i/8MBY9Rt4bUvHDCkZ9eDRnviIXmQBx0D1vAbOGrsCn1/BJaauqjldxlkGo0B7GbVO5dDZQFkkbxhMSwjHhA5RDBsAQ+oOMVJaSl82EIbfEwA7fNsgYB7iwZqiS6qUZt8nSeg7ZT52gh7hQs2rbTvQFQwHFgJnAGVyjR5IU92c4N8MBr2J7450qBQNA/t4wGipe5kSTfa9QV8xX+FbTM7qn3f0Sx5iElti+xBTKC4WTK4YWJG63fSFaC7LXpmu4pYcTFIxKbiPDZGsf0dm5ecXQsSJ4xJUz+A/tbsI2ZWI8knq328IQ/wGoFG86QTK2Gciz+bFZp+1eQX6kPMwSgqtZ9dUm0Rw/E3wn6SOGkkyggqVMVra5EoF7TBDYs4mbW7Lx4NA1dDzdQ5/Sl0leNwQmHx59s3tntLNM3ZoRLbU/3yJriCs2JyJeLno17C0Uy1rsFj0c3vZKBo3NF8fF5RAKdEenJ0mkmIqfL8z7+HCDjRFtN9jTzua/8KJDU3uYHpgUuStzkX85dkXYIcfIqZ4cTgtGiJ+sb5mL2DanE+h7kS1HRtcMqOsMrjevkIiKorUaQuXQx6t9xm2Hj1wxC2o9xYAWkPRgMRPNJ7kXgSTQeu4ohk=
deploy:
  provider: pypi
  skip_cleanup: true
  user: wray
  password:
    secure: QGu4cJZHzm2f99x+IddWvO6NvwBFT0GcGBf6no5rRqw4ISjdGxd+W3jl8V7qsucA1SpGlzAQxwQfCm72prkIYvUtu12mDy7qVeZT6gMIgG7LmrXojhiRNOAjzXCMdC3wCgnxAVqg0R5KD5V9fXr9EVrfKf/HFA+u6U6Ds2OswVCnUnRB02/pKXWflX50nRZXGuUA9ea3l35ldIDXK0vvcSWYaSb3ECLO0y9OU2sv5N7LfLazCr12+FdiAIfePEHFVUkStnoFsDAKSmhkwFCYEnEZcpWh3tn0mRmLvkBRX+vDn/CJxxy98Uw/fD/sp/8q4WpjHjcRA3hR645OFPjKjPrRXb0LvqB3IeCNADytLvelcYZI18VLL+fEhku9mn/Xvl5oRj8IeQLXFtiF4UJfApOymwJe8nGbYLNhwvVaam1WrL+pmH+j5Ao3olXKGzJDEBDJrKBkBJkLsJcnNbi2dnjZ0oFdjGAkmJxQDEsG6bINi45sjUDzUFlZwnRiPEB1kTUoXjVt5gr55a+Xegh6vABGleex/0D8irAF/SuRaN7C9aiqAL5II+zy/zybWmuFK0N8G8v2yX21wSX70eE2tj11TBSjjwdu2WGG3UZ3mrdpGFsbNEEwUe3x9DKg3s4k+F9Z9w3ljXJJtbSPzSyrV1g++jtxnwwAgRqb9/Zvypo=
